---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-root-app
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: aws
  source:
    repoURL: https://github.com/gusta-lab/gitops-crossplane
    targetRevision: main
    path: aws/templates
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true