---
apiVersion: azure.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: sub-gusta-labs
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: crossplane-system
      name: azure-credentials
      key: credentials
