---
apiVersion: pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-azure-azure
spec:
  package: xpkg.upbound.io/upbound/provider-azure-azure:v2.0.1
  runtimeConfigRef:
    apiVersion: pkg.crossplane.io/v1beta1
    kind: DeploymentRuntimeConfig
    name: azure-config

---
apiVersion: pkg.crossplane.io/v1beta1
kind: DeploymentRuntimeConfig
metadata:
  name: azure-config
spec:
  deploymentTemplate:
    spec:
      selector: {}
      template:
        spec:
          containers:
            - name: package-runtime
              args:
                - --poll=1m # Padrão 10 minutos
