---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: argocd-application-controller-pod-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - argocd
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-application-controller
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      relabelings:
        - targetLabel: job
          replacement: argocd-application-controller
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: argocd-server-pod-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - argocd
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-server
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      relabelings:
        - targetLabel: job
          replacement: argocd-server
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: argocd-repo-server-pod-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - argocd
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-repo-server
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      relabelings:
        - targetLabel: job
          replacement: argocd-repo-server
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: argocd-notifications-controller-pod-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  namespaceSelector:
    matchNames:
      - argocd
  selector:
    matchLabels:
      app.kubernetes.io/name: argocd-notifications-controller
  podMetricsEndpoints:
    - port: metrics
      path: /metrics
      interval: 30s
      relabelings:
        - targetLabel: job
          replacement: argocd-notifications-controller
