---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: monitors-argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infra
  source:
    repoURL: https://github.com/gusta-lab/gitops-infra
    targetRevision: main
    path: k8s-local/manifests/argocd
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
