apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: azure-compositions
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: azure
  source:
    repoURL: https://github.com/gusta-lab/azure-crossplane
    targetRevision: main
    path: compositions
    directory:
      recurse: true
      exclude: '**/examples/**'
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
